export const client = {
  name: "Elite Landscaping Services",
  tagline: "Professional landscaping services in Irvine",
  phone: "(949) 123-4567",
  email: "john@elitelandscaping.com",
  address: "123 Main St",
  city: "Irvine",
  state: "CA",
  serviceArea: ["Irvine"],
  primaryColor: "#4a1a6b",
  industry: "landscaping",
  services: ["Lawn care","Garden design","Irrigation","Tree trimming","Mulching","Sod installation","Leaf removal"],
  cmsUrl: "https://cms.sebvia.com",
  tenantSlug: "elite-landscaping-services",
  googleAnalyticsId: '',
  domain: "elitelandscaping.sebvia.com",
};
